rule XSSAttack {
    meta:
        description = "检测跨站脚本(XSS)攻击"
        author = "Mobile Platform Creator Security Team"
        date = "2024-03-20"
        severity = 5

    strings:
        $s1 = "<script" nocase
        $s2 = "javascript:" nocase
        $s3 = "onerror=" nocase
        $s4 = "onload=" nocase
        $s5 = "onclick=" nocase
        $s6 = "onmouseover=" nocase
        $s7 = "onmouseout=" nocase
        $s8 = "onmouseenter=" nocase
        $s9 = "onmouseleave=" nocase
        $s10 = "onmousedown=" nocase
        $s11 = "onmouseup=" nocase
        $s12 = "onmousemove=" nocase
        $s13 = "onkeydown=" nocase
        $s14 = "onkeyup=" nocase
        $s15 = "onkeypress=" nocase
        $s16 = "onfocus=" nocase
        $s17 = "onblur=" nocase
        $s18 = "onchange=" nocase
        $s19 = "onsubmit=" nocase
        $s20 = "onreset=" nocase
        $s21 = "onselect=" nocase
        $s22 = "onabort=" nocase
        $s23 = "ondblclick=" nocase
        $s24 = "oncontextmenu=" nocase
        $s25 = "ondrag=" nocase
        $s26 = "ondragend=" nocase
        $s27 = "ondragenter=" nocase
        $s28 = "ondragleave=" nocase
        $s29 = "ondragover=" nocase
        $s30 = "ondragstart=" nocase
        $s31 = "ondrop=" nocase
        $s32 = "onresize=" nocase
        $s33 = "onscroll=" nocase
        $s34 = "onunload=" nocase
        $s35 = "onwheel=" nocase
        $s36 = "onzoom=" nocase
        $s37 = "oncut=" nocase
        $s38 = "oncopy=" nocase
        $s39 = "onpaste=" nocase
        $s40 = "onbeforecut=" nocase
        $s41 = "onbeforecopy=" nocase
        $s42 = "onbeforepaste=" nocase
        $s43 = "onbeforeunload=" nocase
        $s44 = "onhashchange=" nocase
        $s45 = "onmessage=" nocase
        $s46 = "ononline=" nocase
        $s47 = "onoffline=" nocase
        $s48 = "onpopstate=" nocase
        $s49 = "onstorage=" nocase
        $s50 = "onunhandledrejection=" nocase
        $s51 = "eval(" nocase
        $s52 = "document.write(" nocase
        $s53 = "document.writeln(" nocase
        $s54 = "document.domain" nocase
        $s55 = "document.cookie" nocase
        $s56 = "document.location" nocase
        $s57 = "document.URL" nocase
        $s58 = "document.referrer" nocase
        $s59 = "document.forms" nocase
        $s60 = "document.images" nocase
        $s61 = "document.links" nocase
        $s62 = "document.anchors" nocase
        $s63 = "document.embeds" nocase
        $s64 = "document.plugins" nocase
        $s65 = "document.applets" nocase
        $s66 = "document.scripts" nocase
        $s67 = "document.styleSheets" nocase
        $s68 = "document.title" nocase
        $s69 = "document.body" nocase
        $s70 = "document.head" nocase
        $s71 = "document.documentElement" nocase
        $s72 = "document.doctype" nocase
        $s73 = "document.implementation" nocase
        $s74 = "document.inputEncoding" nocase
        $s75 = "document.characterSet" nocase
        $s76 = "document.charset" nocase
        $s77 = "document.defaultView" nocase
        $s78 = "document.designMode" nocase
        $s79 = "document.dir" nocase
        $s80 = "document.readyState" nocase
        $s81 = "document.visibilityState" nocase
        $s82 = "document.hidden" nocase
        $s83 = "document.webkitVisibilityState" nocase
        $s84 = "document.webkitHidden" nocase
        $s85 = "document.mozVisibilityState" nocase
        $s86 = "document.mozHidden" nocase
        $s87 = "document.msVisibilityState" nocase
        $s88 = "document.msHidden" nocase
        $s89 = "document.activeElement" nocase
        $s90 = "document.hasFocus()" nocase
        $s91 = "document.execCommand(" nocase
        $s92 = "document.queryCommandEnabled(" nocase
        $s93 = "document.queryCommandIndeterm(" nocase
        $s94 = "document.queryCommandState(" nocase
        $s95 = "document.queryCommandSupported(" nocase
        $s96 = "document.queryCommandValue(" nocase
        $s97 = "document.getElementsByTagName(" nocase
        $s98 = "document.getElementsByClassName(" nocase
        $s99 = "document.getElementsByName(" nocase
        $s100 = "document.getElementById(" nocase
        $s101 = "document.querySelector(" nocase
        $s102 = "document.querySelectorAll(" nocase
        $s103 = "document.createEvent(" nocase
        $s104 = "document.createEventObject(" nocase
        $s105 = "document.createRange(" nocase
        $s106 = "document.createTreeWalker(" nocase
        $s107 = "document.createNodeIterator(" nocase
        $s108 = "document.createDocumentFragment(" nocase
        $s109 = "document.createTextNode(" nocase
        $s110 = "document.createComment(" nocase
        $s111 = "document.createCDATASection(" nocase
        $s112 = "document.createProcessingInstruction(" nocase
        $s113 = "document.createAttribute(" nocase
        $s114 = "document.createAttributeNS(" nocase
        $s115 = "document.createElement(" nocase
        $s116 = "document.createElementNS(" nocase
        $s117 = "document.createEntityReference(" nocase
        $s118 = "document.importNode(" nocase
        $s119 = "document.adoptNode(" nocase
        $s120 = "document.normalize(" nocase
        $s121 = "document.renameNode(" nocase
        $s122 = "document.open(" nocase
        $s123 = "document.close(" nocase
        $s124 = "document.clear(" nocase
        $s125 = "document.captureEvents(" nocase
        $s126 = "document.releaseEvents(" nocase
        $s127 = "document.hasFocus(" nocase
        $s128 = "document.execCommand(" nocase
        $s129 = "document.queryCommandEnabled(" nocase
        $s130 = "document.queryCommandIndeterm(" nocase
        $s131 = "document.queryCommandState(" nocase
        $s132 = "document.queryCommandSupported(" nocase
        $s133 = "document.queryCommandValue(" nocase
        $s134 = "window.open(" nocase
        $s135 = "window.alert(" nocase
        $s136 = "window.confirm(" nocase
        $s137 = "window.prompt(" nocase
        $s138 = "window.print(" nocase
        $s139 = "window.focus(" nocase
        $s140 = "window.blur(" nocase
        $s141 = "window.close(" nocase
        $s142 = "window.stop(" nocase
        $s143 = "window.scroll(" nocase
        $s144 = "window.scrollTo(" nocase
        $s145 = "window.scrollBy(" nocase
        $s146 = "window.moveTo(" nocase
        $s147 = "window.moveBy(" nocase
        $s148 = "window.resizeTo(" nocase
        $s149 = "window.resizeBy(" nocase
        $s150 = "window.setTimeout(" nocase
        $s151 = "window.setInterval(" nocase
        $s152 = "window.clearTimeout(" nocase
        $s153 = "window.clearInterval(" nocase
        $s154 = "window.requestAnimationFrame(" nocase
        $s155 = "window.cancelAnimationFrame(" nocase
        $s156 = "window.requestIdleCallback(" nocase
        $s157 = "window.cancelIdleCallback(" nocase
        $s158 = "window.matchMedia(" nocase
        $s159 = "window.getComputedStyle(" nocase
        $s160 = "window.getDefaultComputedStyle(" nocase
        $s161 = "window.scrollX" nocase
        $s162 = "window.scrollY" nocase
        $s163 = "window.pageXOffset" nocase
        $s164 = "window.pageYOffset" nocase
        $s165 = "window.innerWidth" nocase
        $s166 = "window.innerHeight" nocase
        $s167 = "window.outerWidth" nocase
        $s168 = "window.outerHeight" nocase
        $s169 = "window.screenX" nocase
        $s170 = "window.screenY" nocase
        $s171 = "window.screenLeft" nocase
        $s172 = "window.screenTop" nocase
        $s173 = "window.devicePixelRatio" nocase
        $s174 = "window.colorDepth" nocase
        $s175 = "window.pixelDepth" nocase
        $s176 = "window.screen" nocase
        $s177 = "window.history" nocase
        $s178 = "window.location" nocase
        $s179 = "window.navigator" nocase
        $s180 = "window.document" nocase
        $s181 = "window.localStorage" nocase
        $s182 = "window.sessionStorage" nocase
        $s183 = "window.indexedDB" nocase
        $s184 = "window.crypto" nocase
        $s185 = "window.performance" nocase
        $s186 = "window.console" nocase
        $s187 = "window.JSON" nocase
        $s188 = "window.Math" nocase
        $s189 = "window.Date" nocase
        $s190 = "window.RegExp" nocase
        $s191 = "window.String" nocase
        $s192 = "window.Number" nocase
        $s193 = "window.Boolean" nocase
        $s194 = "window.Object" nocase
        $s195 = "window.Array" nocase
        $s196 = "window.Function" nocase
        $s197 = "window.Error" nocase
        $s198 = "window.EvalError" nocase
        $s199 = "window.RangeError" nocase
        $s200 = "window.ReferenceError" nocase
        $s201 = "window.SyntaxError" nocase
        $s202 = "window.TypeError" nocase
        $s203 = "window.URIError" nocase
        $s204 = "window.Int8Array" nocase
        $s205 = "window.Uint8Array" nocase
        $s206 = "window.Uint8ClampedArray" nocase
        $s207 = "window.Int16Array" nocase
        $s208 = "window.Uint16Array" nocase
        $s209 = "window.Int32Array" nocase
        $s210 = "window.Uint32Array" nocase
        $s211 = "window.Float32Array" nocase
        $s212 = "window.Float64Array" nocase
        $s213 = "window.DataView" nocase
        $s214 = "window.ArrayBuffer" nocase
        $s215 = "window.Promise" nocase
        $s216 = "window.Generator" nocase
        $s217 = "window.GeneratorFunction" nocase
        $s218 = "window.AsyncFunction" nocase
        $s219 = "window.Proxy" nocase
        $s220 = "window.Reflect" nocase
        $s221 = "window.Symbol" nocase
        $s222 = "window.Set" nocase
        $s223 = "window.Map" nocase
        $s224 = "window.WeakSet" nocase
        $s225 = "window.WeakMap" nocase
        $s226 = "window.Intl" nocase
        $s227 = "window.WebAssembly" nocase
        $s228 = "window.URL" nocase
        $s229 = "window.URLSearchParams" nocase
        $s230 = "window.FormData" nocase
        $s231 = "window.FileReader" nocase
        $s232 = "window.File" nocase
        $s233 = "window.Blob" nocase
        $s234 = "window.FileList" nocase
        $s235 = "window.FileSystem" nocase
        $s236 = "window.FileSystemEntry" nocase
        $s237 = "window.FileSystemFileEntry" nocase
        $s238 = "window.FileSystemDirectoryEntry" nocase
        $s239 = "window.FileSystemDirectoryReader" nocase
        $s240 = "window.FileSystemFlags" nocase
        $s241 = "window.FileSystemHandle" nocase
        $s242 = "window.FileSystemFileHandle" nocase
        $s243 = "window.FileSystemDirectoryHandle" nocase
        $s244 = "window.FileSystemWritableFileStream" nocase
        $s245 = "window.FileSystemSyncAccessHandle" nocase
        $s246 = "window.FileSystemAccessHandle" nocase
        $s247 = "window.FileSystemFileHandle" nocase
        $s248 = "window.FileSystemDirectoryHandle" nocase
        $s249 = "window.FileSystemWritableFileStream" nocase
        $s250 = "window.FileSystemSyncAccessHandle" nocase
        $s251 = "window.FileSystemAccessHandle" nocase
        $s252 = "window.FileSystemFileHandle" nocase
        $s253 = "window.FileSystemDirectoryHandle" nocase
        $s254 = "window.FileSystemWritableFileStream" nocase
        $s255 = "window.FileSystemSyncAccessHandle" nocase
        $s256 = "window.FileSystemAccessHandle" nocase
        $s257 = "window.FileSystemFileHandle" nocase
        $s258 = "window.FileSystemDirectoryHandle" nocase
        $s259 = "window.FileSystemWritableFileStream" nocase
        $s260 = "window.FileSystemSyncAccessHandle" nocase
        $s261 = "window.FileSystemAccessHandle" nocase
        $s262 = "window.FileSystemFileHandle" nocase
        $s263 = "window.FileSystemDirectoryHandle" nocase
        $s264 = "window.FileSystemWritableFileStream" nocase
        $s265 = "window.FileSystemSyncAccessHandle" nocase
        $s266 = "window.FileSystemAccessHandle" nocase
        $s267 = "window.FileSystemFileHandle" nocase
        $s268 = "window.FileSystemDirectoryHandle" nocase
        $s269 = "window.FileSystemWritableFileStream" nocase
        $s270 = "window.FileSystemSyncAccessHandle" nocase
        $s271 = "window.FileSystemAccessHandle" nocase
        $s272 = "window.FileSystemFileHandle" nocase
        $s273 = "window.FileSystemDirectoryHandle" nocase
        $s274 = "window.FileSystemWritableFileStream" nocase
        $s275 = "window.FileSystemSyncAccessHandle" nocase
        $s276 = "window.FileSystemAccessHandle" nocase
        $s277 = "window.FileSystemFileHandle" nocase
        $s278 = "window.FileSystemDirectoryHandle" nocase
        $s279 = "window.FileSystemWritableFileStream" nocase
        $s280 = "window.FileSystemSyncAccessHandle" nocase
        $s281 = "window.FileSystemAccessHandle" nocase
        $s282 = "window.FileSystemFileHandle" nocase
        $s283 = "window.FileSystemDirectoryHandle" nocase
        $s284 = "window.FileSystemWritableFileStream" nocase
        $s285 = "window.FileSystemSyncAccessHandle" nocase
        $s286 = "window.FileSystemAccessHandle" nocase
        $s287 = "window.FileSystemFileHandle" nocase
        $s288 = "window.FileSystemDirectoryHandle" nocase
        $s289 = "window.FileSystemWritableFileStream" nocase
        $s290 = "window.FileSystemSyncAccessHandle" nocase
        $s291 = "window.FileSystemAccessHandle" nocase
        $s292 = "window.FileSystemFileHandle" nocase
        $s293 = "window.FileSystemDirectoryHandle" nocase
        $s294 = "window.FileSystemWritableFileStream" nocase
        $s295 = "window.FileSystemSyncAccessHandle" nocase
        $s296 = "window.FileSystemAccessHandle" nocase
        $s297 = "window.FileSystemFileHandle" nocase
        $s298 = "window.FileSystemDirectoryHandle" nocase
        $s299 = "window.FileSystemWritableFileStream" nocase
        $s300 = "window.FileSystemSyncAccessHandle" nocase

    condition:
        any of ($s*)
} 